---
 - name: apt_get update
   apt: update_cache=yes
 - name: install dependecy
   apt: name={{item}} state=present
   with_items:
         - apt-transport-https
         - ca-certificates
         - curl
         - software-properties-common
         - python3-pip
         - python3-dev
 - name: install docker-py
   pip: name=docker-py state=present

 - name: add official key docker
   apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present
 - name: add official repository docker
   apt_repository:
     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
     state: present
 - name: apt_get update
   apt: update_cache=yes

 - name: install docker
   apt: name=docker-ce state=present force=yes

 - name: pull postgres image
   docker_image: name=postgres state=present tag=latest
 - name: pull base image ubuntu
   docker_image: name=ubuntu state=present tag=16.04



